// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBouAC-jA1BpAJVr9hpUVcLLhNrqlLhLSE',
    appId: '1:234878946786:web:6471a3ca6be4e03fd1fdbb',
    messagingSenderId: '234878946786',
    projectId: 'ecommerce-da687',
    authDomain: 'ecommerce-da687.firebaseapp.com',
    storageBucket: 'ecommerce-da687.appspot.com',
    measurementId: 'G-4QF2RE110Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_urRCW377i7Ucm1isAz3roZ8nM8ZzRo',
    appId: '1:234878946786:android:7f1b10ee5e5c2e75d1fdbb',
    messagingSenderId: '234878946786',
    projectId: 'ecommerce-da687',
    storageBucket: 'ecommerce-da687.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdM0ggcqlaFKwDmJJvbPnrtmuTKfEmHn8',
    appId: '1:234878946786:ios:ec9995b89944155cd1fdbb',
    messagingSenderId: '234878946786',
    projectId: 'ecommerce-da687',
    storageBucket: 'ecommerce-da687.appspot.com',
    iosClientId: '234878946786-9pvi8oikfg9iiurh1eithsgfmp3v2iqn.apps.googleusercontent.com',
    iosBundleId: 'com.ecommerce.app',
  );
}
